version: 1
name: 'Jet Met Rates'

input:
  files:
       - /afs/cern.ch/user/m/mamiesko/public/L1TestNTuples/l1NTuple_algo_PHIRING_mc_Nu/L1Ntuple.root
  sample:
    name: nuGun
    title: Run 3 MC
  trigger:
    name: PHIRING
    title: L1
  pileup_file: ""
  run_number:
  ntuple_map_file: config/ntuple_content_mc.yaml

analysis:
  load_trees:
    - event
    - upgrade
    - emuUpgrade
    - genTree

  do_fit: True
  pu_type: 0PU
  pu_bins: [0, 999]
  thresholds:
    HT:           [200, 400]
    METBE:        [80, 150]
    METHF:        [80, 150]
    JetET_BE:     [100, 200]
    JetET_HF:     [100, 200]
# these are the fixed rates we want to use to
# compare different emulations at different
# thresholds that give this rate, from TDR Menu
  rates:
    HT:           2 #kHz
    METBE:        1
    METHF:        1
    JetET_BE:     2
    JetET_HF:     0.1 # guess

  analyzers:
     HW_Emu_jetMet_rates:
       module: cmsl1t.analyzers.HW_Emu_jetMet_rates
  producers:
    l1Sums:
      module: cmsl1t.producers.l1sums
      inputs:
        - L1Upgrade_sumBx
        - L1Upgrade_sumType
        - L1Upgrade_sumEt
        - L1Upgrade_sumPhi
      outputs:
        - l1Sums
    l1EmuSums:
      module: cmsl1t.producers.l1sums
      inputs:
        - emu_L1Upgrade_sumBx
        - emu_L1Upgrade_sumType
        - emu_L1Upgrade_sumEt
        - emu_L1Upgrade_sumPhi
      outputs:
        - l1EmuSums
    genSums:
      module: cmsl1t.producers.gensums
      inputs:
        - Generator_jetPt
        - Generator_jetEta
        - Generator_partId
        - Generator_partPhi
        - Generator_partPt
        - Generator_partEta
      outputs:
        - genSums
    goodGenJets:
      module: cmsl1t.producers.jets
      inputs:
        - Generator_jetPt
        - Generator_jetEta
        - Generator_jetPhi
      jetType: Gen
      outputs:
        - goodGenJets
    l1Jets:
      module: cmsl1t.producers.jets
      inputs:
        - L1Upgrade_jetEt
        - L1Upgrade_jetEta
        - L1Upgrade_jetPhi
        - L1Upgrade_jetBx
      jetType: L1
      filter: null
      outputs:
        - l1Jets
    l1EmuJets:
      module: cmsl1t.producers.jets
      inputs:
        - emu_L1Upgrade_jetEt
        - emu_L1Upgrade_jetEta
        - emu_L1Upgrade_jetPhi
        - emu_L1Upgrade_jetBx
      jetType: L1
      filter: null
      outputs:
        - l1EmuJets

output:
  template:
     - output/zb_rates
     - "{date}_{sample_name}_{trigger_name}"
